package NewsApp;


/**
* NewsApp/_NewsStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from News.idl
* Wednesday, April 22, 2015 6:44:57 PM IST
*/

public class _NewsStub extends org.omg.CORBA.portable.ObjectImpl implements NewsApp.News
{

  public int registerClient (String username, String password, String type)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerClient", true);
                $out.write_string (username);
                $out.write_string (password);
                $out.write_string (type);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registerClient (username, password, type        );
            } finally {
                _releaseReply ($in);
            }
  } // registerClient

  public int login (String username, String password, String type)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("login", true);
                $out.write_string (username);
                $out.write_string (password);
                $out.write_string (type);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return login (username, password, type        );
            } finally {
                _releaseReply ($in);
            }
  } // login

  public NewsApp.NewsPackage.News getTopHeadLines (String domain, int numberOfNews)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTopHeadLines", true);
                $out.write_string (domain);
                $out.write_long (numberOfNews);
                $in = _invoke ($out);
                NewsApp.NewsPackage.News $result = NewsApp.NewsPackage.NewsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTopHeadLines (domain, numberOfNews        );
            } finally {
                _releaseReply ($in);
            }
  } // getTopHeadLines

  public NewsApp.NewsPackage.News getShortNews (String domain, String id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getShortNews", true);
                $out.write_string (domain);
                $out.write_string (id);
                $in = _invoke ($out);
                NewsApp.NewsPackage.News $result = NewsApp.NewsPackage.NewsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getShortNews (domain, id        );
            } finally {
                _releaseReply ($in);
            }
  } // getShortNews

  public NewsApp.NewsPackage.News getFullNews (String domain, String id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getFullNews", true);
                $out.write_string (domain);
                $out.write_string (id);
                $in = _invoke ($out);
                NewsApp.NewsPackage.News $result = NewsApp.NewsPackage.NewsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getFullNews (domain, id        );
            } finally {
                _releaseReply ($in);
            }
  } // getFullNews

  public NewsApp.NewsPackage.News getTopShortNews (String domain, int numberOfNews)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTopShortNews", true);
                $out.write_string (domain);
                $out.write_long (numberOfNews);
                $in = _invoke ($out);
                NewsApp.NewsPackage.News $result = NewsApp.NewsPackage.NewsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTopShortNews (domain, numberOfNews        );
            } finally {
                _releaseReply ($in);
            }
  } // getTopShortNews

  public NewsApp.NewsPackage.News getTopFullNews (String domain, int numberOfNews)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTopFullNews", true);
                $out.write_string (domain);
                $out.write_long (numberOfNews);
                $in = _invoke ($out);
                NewsApp.NewsPackage.News $result = NewsApp.NewsPackage.NewsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTopFullNews (domain, numberOfNews        );
            } finally {
                _releaseReply ($in);
            }
  } // getTopFullNews

  public int addNews (String domain, String news)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addNews", true);
                $out.write_string (domain);
                $out.write_string (news);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addNews (domain, news        );
            } finally {
                _releaseReply ($in);
            }
  } // addNews

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:NewsApp/News:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _NewsStub
