package NewsApp;


/**
* NewsApp/NewsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from News.idl
* Wednesday, April 22, 2015 6:44:57 PM IST
*/

public interface NewsOperations 
{
  int registerClient (String username, String password, String type);
  int login (String username, String password, String type);
  NewsApp.NewsPackage.News getTopHeadLines (String domain, int numberOfNews);
  NewsApp.NewsPackage.News getShortNews (String domain, String id);
  NewsApp.NewsPackage.News getFullNews (String domain, String id);
  NewsApp.NewsPackage.News getTopShortNews (String domain, int numberOfNews);
  NewsApp.NewsPackage.News getTopFullNews (String domain, int numberOfNews);
  int addNews (String domain, String news);
  void shutdown ();
} // interface NewsOperations
