package NewsApp;


/**
* NewsApp/NewsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from News.idl
* Wednesday, April 22, 2015 6:44:57 PM IST
*/

public abstract class NewsPOA extends org.omg.PortableServer.Servant
 implements NewsApp.NewsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerClient", new java.lang.Integer (0));
    _methods.put ("login", new java.lang.Integer (1));
    _methods.put ("getTopHeadLines", new java.lang.Integer (2));
    _methods.put ("getShortNews", new java.lang.Integer (3));
    _methods.put ("getFullNews", new java.lang.Integer (4));
    _methods.put ("getTopShortNews", new java.lang.Integer (5));
    _methods.put ("getTopFullNews", new java.lang.Integer (6));
    _methods.put ("addNews", new java.lang.Integer (7));
    _methods.put ("shutdown", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // NewsApp/News/registerClient
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String type = in.read_string ();
         int $result = (int)0;
         $result = this.registerClient (username, password, type);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // NewsApp/News/login
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String type = in.read_string ();
         int $result = (int)0;
         $result = this.login (username, password, type);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // NewsApp/News/getTopHeadLines
       {
         String domain = in.read_string ();
         int numberOfNews = in.read_long ();
         NewsApp.NewsPackage.News $result = null;
         $result = this.getTopHeadLines (domain, numberOfNews);
         out = $rh.createReply();
         NewsApp.NewsPackage.NewsHelper.write (out, $result);
         break;
       }

       case 3:  // NewsApp/News/getShortNews
       {
         String domain = in.read_string ();
         String id = in.read_string ();
         NewsApp.NewsPackage.News $result = null;
         $result = this.getShortNews (domain, id);
         out = $rh.createReply();
         NewsApp.NewsPackage.NewsHelper.write (out, $result);
         break;
       }

       case 4:  // NewsApp/News/getFullNews
       {
         String domain = in.read_string ();
         String id = in.read_string ();
         NewsApp.NewsPackage.News $result = null;
         $result = this.getFullNews (domain, id);
         out = $rh.createReply();
         NewsApp.NewsPackage.NewsHelper.write (out, $result);
         break;
       }

       case 5:  // NewsApp/News/getTopShortNews
       {
         String domain = in.read_string ();
         int numberOfNews = in.read_long ();
         NewsApp.NewsPackage.News $result = null;
         $result = this.getTopShortNews (domain, numberOfNews);
         out = $rh.createReply();
         NewsApp.NewsPackage.NewsHelper.write (out, $result);
         break;
       }

       case 6:  // NewsApp/News/getTopFullNews
       {
         String domain = in.read_string ();
         int numberOfNews = in.read_long ();
         NewsApp.NewsPackage.News $result = null;
         $result = this.getTopFullNews (domain, numberOfNews);
         out = $rh.createReply();
         NewsApp.NewsPackage.NewsHelper.write (out, $result);
         break;
       }

       case 7:  // NewsApp/News/addNews
       {
         String domain = in.read_string ();
         String news = in.read_string ();
         int $result = (int)0;
         $result = this.addNews (domain, news);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // NewsApp/News/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:NewsApp/News:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public News _this() 
  {
    return NewsHelper.narrow(
    super._this_object());
  }

  public News _this(org.omg.CORBA.ORB orb) 
  {
    return NewsHelper.narrow(
    super._this_object(orb));
  }


} // class NewsPOA
