package NewsApp.NewsPackage;


/**
* NewsApp/NewsPackage/News.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from News.idl
* Wednesday, April 22, 2015 6:44:57 PM IST
*/

public final class News implements org.omg.CORBA.portable.IDLEntity
{
  public String serverName = null;
  public String id[] = null;
  public String news[] = null;
  public String imageLink[] = null;
  public String domain[] = null;

  public News ()
  {
  } // ctor

  public News (String _serverName, String[] _id, String[] _news, String[] _imageLink, String[] _domain)
  {
    serverName = _serverName;
    id = _id;
    news = _news;
    imageLink = _imageLink;
    domain = _domain;
  } // ctor

} // class News
