package NewsApp.NewsPackage;


/**
* NewsApp/NewsPackage/NewsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from News.idl
* Wednesday, April 22, 2015 6:44:57 PM IST
*/

abstract public class NewsHelper
{
  private static String  _id = "IDL:NewsApp/News/News:1.0";

  public static void insert (org.omg.CORBA.Any a, NewsApp.NewsPackage.News that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static NewsApp.NewsPackage.News extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "serverName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "news",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "imageLink",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "domain",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (NewsApp.NewsPackage.NewsHelper.id (), "News", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static NewsApp.NewsPackage.News read (org.omg.CORBA.portable.InputStream istream)
  {
    NewsApp.NewsPackage.News value = new NewsApp.NewsPackage.News ();
    value.serverName = istream.read_string ();
    int _len0 = istream.read_long ();
    value.id = new String[_len0];
    for (int _o1 = 0;_o1 < value.id.length; ++_o1)
      value.id[_o1] = istream.read_string ();
    int _len1 = istream.read_long ();
    value.news = new String[_len1];
    for (int _o2 = 0;_o2 < value.news.length; ++_o2)
      value.news[_o2] = istream.read_string ();
    int _len2 = istream.read_long ();
    value.imageLink = new String[_len2];
    for (int _o3 = 0;_o3 < value.imageLink.length; ++_o3)
      value.imageLink[_o3] = istream.read_string ();
    int _len3 = istream.read_long ();
    value.domain = new String[_len3];
    for (int _o4 = 0;_o4 < value.domain.length; ++_o4)
      value.domain[_o4] = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, NewsApp.NewsPackage.News value)
  {
    ostream.write_string (value.serverName);
    ostream.write_long (value.id.length);
    for (int _i0 = 0;_i0 < value.id.length; ++_i0)
      ostream.write_string (value.id[_i0]);
    ostream.write_long (value.news.length);
    for (int _i1 = 0;_i1 < value.news.length; ++_i1)
      ostream.write_string (value.news[_i1]);
    ostream.write_long (value.imageLink.length);
    for (int _i2 = 0;_i2 < value.imageLink.length; ++_i2)
      ostream.write_string (value.imageLink[_i2]);
    ostream.write_long (value.domain.length);
    for (int _i3 = 0;_i3 < value.domain.length; ++_i3)
      ostream.write_string (value.domain[_i3]);
  }

}
